# Generated by Django 6.0.3 on 2026-03-27 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Anket Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.CharField(max_length=200)),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='anketler.anket')),
            ],
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secenek_metni', models.CharField(max_length=200)),
                ('oy_sayisi', models.IntegerField(default=0)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='anketler.soru')),
            ],
        ),
    ]
